chore: regular update

diff --git a/rebos/.config/rebos/hooks/post_init_pkgs_add b/rebos/.config/rebos/hooks/post_init_pkgs_add
--- a/rebos/.config/rebos/hooks/post_init_pkgs_add
+++ b/rebos/.config/rebos/hooks/post_init_pkgs_add
@@ -1,41 +1,51 @@
 #!/usr/bin/env bash
 
 # Set rustup toolchain to stable
-# rustup default stable || exit 1
+rustup default stable >/dev/null 2>&1 || exit 1
 
-# warn_notice() {
-# 	echo -e "\033[1;33mNOTICE: $1\033[0m"
-# }
+# INFO: functions starting with setup_* are called by rebos
+# These functions downloads files from internet or some from my old commits
+# and installs locally. These files are not available on pacman/aur repos, or
+# are not compatible and working with my current setup.
+# Additionally downloading files using rebos hooks actully helped me by reducing
+# dotfiles github repo size from 76MB to 2MB.
+# These functions are optimized and makes early exit if the file already exists
 
 # This function installs collection of rofi custom applets
 # github: https://github.com/adi1090x/rofi
 setup_rofi() {
-	[ -d "$HOME/.config/rofi" ] && return # if configs already exists
-	set -e                                # automatically exits if any of the commands fails
-	local tempdir="/tmp/rofi-collection"
-	[ -d "$tempdir" ] && rm -rf "$tempdir"
-	git clone --depth=1 https://github.com/adi1090x/rofi.git "$tempdir"
-	cd "$tempdir" && chmod +x setup.sh && ./setup.sh
-	rm -rf "$tempdir"
+  [ -d "$HOME/.config/rofi" ] && return # if configs already exists
+  set -e                                # automatically exits if any of the commands fails
+  local tempdir="/tmp/rofi-collection"
+  [ -d "$tempdir" ] && rm -rf "$tempdir"
+  git clone --depth=1 https://github.com/adi1090x/rofi.git "$tempdir"
+  cd "$tempdir" && chmod +x setup.sh && ./setup.sh
+  rm -rf "$tempdir"
 }
 
 setup_fonts() {
-	# This downloads fonts from my old commit, if font doesn't exist
-	set -e # automatically exits if any of the commands fails
-	local dest_dir="$HOME/.local/share/fonts"
-	local fonts_downloaded="false"
-	local commit_sha="2ad06af59746dc3f0d645d451be68bf23da6cfd7"
-	local fonts=("GrapeNuts-Regular.ttf" "Icomoon-Feather.ttf" "icons.ttf" "Iosevka-Nerd-Font-Complete.ttf" "RampartOne-Regular.ttf" "JetBrains-Mono-Nerd-Font-Complete.ttf")
-	local base_url="https://raw.githubusercontent.com/sirjager/dotfiles/$commit_sha/assets/.local/share/fonts"
-	[ ! -d "$dest_dir" ] && mkdir -p "$dest_dir"
-	for font in "${fonts[@]}"; do
-		if [ ! -f "$dest_dir/$font" ]; then
-			wget -q "$base_url/$font" -O "$dest_dir/$font" &&
-				echo "Downloaded Font: $font" &&
-				fonts_downloaded="true"
-		fi
-	done
-	[ "$fonts_downloaded" = "true" ] && fc-cache -f >/dev/null 2>&1
+  # These fonts are used in polybar, rofi, and in few of my custom scripts
+  # This functions checks if each fonts is available
+  set -e # automatically exits if any of the commands fails
+  local dest_dir="$HOME/.local/share/fonts"
+  local fonts_downloaded=0
+  local commit_sha="2ad06af59746dc3f0d645d451be68bf23da6cfd7"
+  local fonts=("RampartOne-Regular.ttf")
+  local base_url="https://raw.githubusercontent.com/sirjager/dotfiles/$commit_sha/assets/.local/share/fonts"
+  [ ! -d "$dest_dir" ] && mkdir -p "$dest_dir"
+  for font in "${fonts[@]}"; do
+    if [ ! -f "$dest_dir/$font" ]; then
+      if wget "$base_url/$font" -O "$dest_dir/$font"; then
+        ((fonts_downloaded++))
+        echo "Downloaded missing font: $font"
+      else
+        echo "Failed to download font: $font"
+      fi
+    fi
+  done
+  if ((fonts_downloaded > 0)); then
+    fc-cache -f >/dev/null 2>&1
+  fi
 }
 
 setup_rofi
